version: '3.12'

services:
  db:
    build:
      context: ./stock_sense_storage
      dockerfile: Dockerfile
    container_name: db_microservice
    ports:
      - "5001:5001"
    networks:
      - stock_network

#  stock_data_downloader:
#    build:
#      context: ./stock_sense_retriever
#      dockerfile: Dockerfile
#    container_name: stock_data_downloader_microservice
#    ports:
#      - "5002:5002"
#    networks:
#      - stock_network
#    depends_on:
#      - db
#
#  prediction:
#    build:
#      context: ./stock_sense_prediction
#      dockerfile: Dockerfile
#    container_name: prediction_microservice
#    ports:
#      - "5003:5003"
#    networks:
#      - stock_network
#    depends_on:
#      - db
#
#  ui:
#    build:
#      context: ./stock_sense_ui
#      dockerfile: Dockerfile
#    container_name: ui_microservice
#    ports:
#      - "5004:5004"
#    networks:
#      - stock_network
#    depends_on:
#      - prediction
#      - stock_data_downloader

networks:
  stock_network:
    driver: bridge
